sudo: false
language: node_js
cache:
  bundler: true
  directories:
    - node_modules
notifications:
  flowdock: e7454f5285e7b9ab67009802d5560490
node_js:
- '0.10'
before_deploy: npm run precompile
deploy:
- provider: s3
  access_key_id: AKIAIT4X4NDGM2WVL6VA
  secret_access_key:
    secure: L8htzfLUPj1Km5bcDEwQKoMrv2W5AW8IdlK2udn/23IIkBh3V6yFpebmE/VG6HhIVBAXVVQ/HvaSrcQnE+x+0mlj6V5iywdrUtYIa+zREDXgI+yfeFWeizMn00OxLeq+l0kqzMQCTdhKGNCOoJG0GdLC8jdgX4Zlv4bfN+eE2e8=
  bucket: octoblu-npm
  upload-dir: meshblu-blink1
  local-dir: build
  acl: public_read
  on:
    tags: true
    all_branches: true
- provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: UB1gj3QZggbLRhZbs4NbZVDK2bnJA1r1bBP86Amj2OmOu6ro732YX4xwi3UPJro++GCdNkPnr4EBQhoFV2EDHdm8oCsf1p3p95AP2Q4MThhJdi94pauWLvWzQTBrvyLsaz0dMEImyyljYvNzNtLYbCQx9GHTGmSxPjcKDdZ5dFM=
  on:
    tags: true
    all_branches: true
