language: node_js
node_js:
- '0.10'
before_install:
  - npm install npm -g
deploy:
  - provider: npm
    skip_cleanup: true
    clean_up: false
    email: serveradmin@octoblu.com
    api_key:
      secure: "To/+o/0Dua9BW7Ob1kW2R1eI3CxEtp2KEbvnWoKEnIL0XiAO79ozQspNZABjhI45O78b7EJFdyJObYSzZhCygdhL2AAGfEKkIFriNDVe7wiqBhmxW29Oc4KYjrxAc0r2xp8sm2BOtWJnETmGPKEki9fAMkCj8pKUSK9CubCTclg="
    on:
      tags: true
      all_branches: true
