language: node_js
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
node_js:
- '0.10'
env:
  - REPLACE_CMD=perl -pe 's;(\\*)(\$([a-zA-Z_][a-zA-Z_0-9]*)|\$\{([a-zA-Z_][a-zA-Z_0-9]*)\})?;substr($1,0,int(length($1)/2)).($2&&length($1)%2?$2:$ENV{$3||$4});eg'
  - S3_ACCESS_KEY_ID=AKIAIT4X4NDGM2WVL6VA
  - secure: VY2gOnSNK1EAqS+WGVFmTGaNzQgAyrRNGumGjtdfvJMuWw+48ie+9g8tBn3jxRpuVL6iFYzbOtvXJfXFBcy39Xp1C1Nwic8kKzCxIMrJZVMaca+1I0klXThi6pbdExY4zcFWVZfhriQG4nU/DoskRiY5a37qtwP/cx/ue10i7cI=
after_success:
- mkdir -p dpl_cd_upload
- $REPLACE_CMD .kubernetes/appspec.yml.tmpl > appspec.yml
- $REPLACE_CMD .kubernetes/meshblu-blink1-pod.yaml.tmpl > .kubernetes/meshblu-blink1-pod.yaml
- zip -r dpl_cd_upload/meshblu-blink1-$TRAVIS_COMMIT.zip * .kubernetes
deploy:
- provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: UB1gj3QZggbLRhZbs4NbZVDK2bnJA1r1bBP86Amj2OmOu6ro732YX4xwi3UPJro++GCdNkPnr4EBQhoFV2EDHdm8oCsf1p3p95AP2Q4MThhJdi94pauWLvWzQTBrvyLsaz0dMEImyyljYvNzNtLYbCQx9GHTGmSxPjcKDdZ5dFM=
  on:
    tags: true
    all_branches: true
- provider: s3
  access_key_id: AKIAIT4X4NDGM2WVL6VA
  secret_access_key: &1
    secure: QcQTI2Bt77/dUDRDYvmKymHvUxiKhM+PytqxMjETaAXlKUDz7mDnQU+lOFmzEqKNx/mB62gFFMEq3jEm8I0L7YbAKfKN+ji8vo3zkJfnsUR7i2SVa267MDTxhaf7If4ZJ8KkBgoX3PtvNMIxDTfTvYBwNH+e+0I0pWjM8R0Q1DQ=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  bucket: octoblu-deploy
  upload_dir: meshblu-blink1
- provider: codedeploy
  access_key_id: AKIAIT4X4NDGM2WVL6VA
  secret_access_key: *1
  bucket: octoblu-deploy
  key: meshblu-blink1/meshblu-blink1-$TRAVIS_COMMIT.zip
  bundle_type: zip
  region: us-west-2
  application: meshblu-blink1
  deployment_group: kubernetes
