language: node_js
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
node_js:
- '0.10'
env:
  global:
  - REPLACE_REGEX='s;(\\*)(\$([a-zA-Z_][a-zA-Z_0-9]*)|\$\{([a-zA-Z_][a-zA-Z_0-9]*)\})?;substr($1,0,int(length($1)/2)).($2&&length($1)%2?$2:$ENV{$3||$4});eg'
  - S3_ACCESS_KEY_ID=AKIAJH2D5IPIRHYJT5IA
  - secure: P6qTbwS6Tw+dUNaPmfjIewMlSYBNzsWAUzoqDBK+xcQBJsut6eYGqFOG9fgw1jEY6iuIw5/FtLTifzE4J+4naImjsQoZkIM9lJpD2XBg9eI1bJDVbq504QNvoFkrz7hAyoWaVTmwTVsRwYp2DNwz91eelZVm0IVBMXHRFAwfGMM=
after_success:
- mkdir -p dpl_cd_upload
- perl -pe $REPLACE_REGEX .kubernetes/appspec.yml.tmpl > appspec.yml
- perl -pe $REPLACE_REGEX .kubernetes/meshblu-blink1-pod.yaml.tmpl > .kubernetes/meshblu-blink1-pod.yaml
- zip -r dpl_cd_upload/meshblu-blink1-$TRAVIS_COMMIT.zip * .kubernetes
deploy:
- provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: UB1gj3QZggbLRhZbs4NbZVDK2bnJA1r1bBP86Amj2OmOu6ro732YX4xwi3UPJro++GCdNkPnr4EBQhoFV2EDHdm8oCsf1p3p95AP2Q4MThhJdi94pauWLvWzQTBrvyLsaz0dMEImyyljYvNzNtLYbCQx9GHTGmSxPjcKDdZ5dFM=
  on:
    tags: true
    all_branches: true
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key: &1
    secure: P7O1XYFZB1AhQP8luf6ilAaOHpHHnmIAUxaPmZ3FLAuIOqRIR2uxY5+dmv6Uom/2ZjrrzweBsh/4BGFeqL3fow3WtSiElJv0ZhEHgJrcPrPvfVcdYx5NGcYpDtsh7yqRoaUvpvq4nYz/pKgWL5VX5/yhwPUnFbvZhYk6gJ4J2Jc=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  bucket: octoblu-deploy
  upload_dir: meshblu-blink1
  on:
    tags: true
    all_branches: true
- provider: codedeploy
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key: *1
  bucket: octoblu-deploy
  key: meshblu-blink1/meshblu-blink1-$TRAVIS_COMMIT.zip
  bundle_type: zip
  region: us-west-2
  application: meshblu-blink1
  deployment_group: kubernetes
  on:
    tags: true
    all_branches: true
